### ISSUE TITLE
feature request - webpack support / setup documentation

### ISSUE THREAD

**Issue by stevies** [aurelia/testing#40]
**I'm submitting a feature request**
- **JSPM OR Webpack AND Version**
  webpack 2.1.0-beta.17
  
  
- **Language:**
  ESNext

**Current behavior:**

Can this be made to work with webpack? 

If I try to get a simple example working using webpack / ESNext - it fails.

I've simply swapped out the bootstrap import to be from 'aurelia-bootstrapper-webpack'.  Maybe I need to do more.  

Can the docs be updated to cover webpack setup, please?  Also, an example of how to configure plugins in the bootstrapping setup would be good. 

```
import {StageComponent} from 'aurelia-testing';
import {bootstrap} from 'aurelia-bootstrapper-webpack';

fdescribe('Test something', () => {
  let component;

  beforeEach(done => {
    component = StageComponent
      .withResources()
      .inView('<div></div>')
      .boundTo({});

    component.bootstrap(aurelia => {
      aurelia.use
        .standardConfiguration()
        .developmentLogging()
    });
  });

  it('should be true', done => {
    component.create(bootstrap).then(() => {
      expect(true).toBeTruthy();
      done();
    });
  });

  afterEach(() => {
    component.dispose();
  });
});
```

Fails with error:

```
21 10 2016 21:24:05.145:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
21 10 2016 21:24:05.147:INFO [launcher]: Launching browser Chrome with unlimited concurrency
21 10 2016 21:24:05.177:INFO [launcher]: Starting browser Chrome
21 10 2016 21:24:06.479:INFO [Chrome 53.0.2785 (Windows 10 0.0.0)]: Connected on socket /#32ZXLgoEA5Kx5absAAAA with id 68937402
WARN: '%cUnhandled rejection TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:57:37)
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:19184:24
From previous event:
    at Promise.then._this2.modulesBeingLoaded.(anonymous function) (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:19183:81)
From previous event:
    at WebpackLoader._import (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:19169:18)
    at WebpackLoader.loadModule (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:19227:17)
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18989:38
From previous event:
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18988:98
    at next (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18737:30)
From previous event:
    at next (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18737:47)
    at runTasks (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18743:10)
    at FrameworkConfiguration.apply (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:19006:12)
    at Aurelia.start (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18623:21)
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:5448:24
From previous event:
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:5443:56
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18461:12
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18387:15
From previous event:
    at onBootstrap (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18385:10)
    at bootstrap (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18459:10)
    at ComponentTester.create (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:5442:12)
    at Object.<anonymous> (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:5707:15)
    at attemptAsync (http://localhost:9876/absoluteD:/WebstormProjects/my_app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:1980:24)
    at QueueRunner.run (http://localhost:9876/absoluteD:/WebstormProjects/my_app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:1935:9)
    at http://localhost:9876/absoluteD:/WebstormProjects/my_app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:1962:16
    at http://localhost:9876/absoluteD:/WebstormProjects/my_app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:1905:9
    at http://localhost:9876/absoluteD:/WebstormProjects/my_app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:1975:11', 'color: red'
WARN: '%cUnhandled rejection TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:57:37)
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:19184:24
From previous event:
    at Promise.then._this2.modulesBeingLoaded.(anonymous function) (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:19183:81)
From previous event:
    at WebpackLoader._import (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:19169:18)
    at WebpackLoader.loadModule (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:19227:17)
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18989:38
From previous event:
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18988:98
    at next (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18737:30)
From previous event:
    at next (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18737:47)
    at runTasks (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18743:10)
    at FrameworkConfiguration.apply (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:19006:12)
    at Aurelia.start (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18623:21)
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:5448:24
From previous event:
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:5443:56
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18461:12
    at http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18387:15
From previous event:
    at onBootstrap (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18385:10)
    at bootstrap (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:18459:10)
    at ComponentTester.create (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:5442:12)
    at Object.<anonymous> (http://localhost:9876/base/spec-bundle.js?7bff0ccb455986d58e4c78ed5b3941847eed3172:5707:15)
    at attemptAsync (http://localhost:9876/absoluteD:/WebstormProjects/my_app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:1980:24)
    at QueueRunner.run (http://localhost:9876/absoluteD:/WebstormProjects/my_app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:1935:9)
    at http://localhost:9876/absoluteD:/WebstormProjects/my_app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:1962:16
    at http://localhost:9876/absoluteD:/WebstormProjects/my_app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:1905:9
    at http://localhost:9876/absoluteD:/WebstormProjects/my_app/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d:1975:11', 'color: red'
  Test something
    × should be true
Chrome 53.0.2785 (Windows 10 0.0.0) Test something should be true FAILED
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    Error: Cannot call ComponentTester.dispose() before ComponentTester.create()
        at ComponentTester.dispose (webpack:///~/aurelia-testing/dist/commonjs/component-tester.js:91:0 <- spec-bundle.js:5475:13)
        at Object.<anonymous> (webpack:///test/unit/views/accreditations.spec.js:28:14 <- spec-bundle.js:5714:15)
```

Same issue running sample code from docs:

```
import {StageComponent} from 'aurelia-testing';
import {bootstrap} from 'aurelia-bootstrapper-webpack';

describe('MyComponent', () => {
  let component;

  beforeEach(() => {
    component = StageComponent
      .withResources('src/resources/elements/my-component')
      .inView('<my-component first-name.bind="firstName"></my-component>')
      .boundTo({ firstName: 'Bob' });
  });

  it('should render first name', done => {
    component.create(bootstrap).then(() => {
      const nameElement = document.querySelector('.firstName');
      expect(nameElement.innerHTML).toBe('Bob');
      done();
    });
  });

  afterEach(() => {
    component.dispose();
  });
});
```

**Comment by EisenbergEffect** [comment]
We have a document that covers basic webpack setup. It isn't published yet but you can take a look at it here: https://github.com/aurelia/framework/blob/master/doc/article/drafts/manual-webpack-configuration.md

**Comment by stevies** [comment]
The question was about testing and using aurelia-testing in a webpack setup (it currently does not work).  The document is helpful if you want to deviate from the @easywebpack approach (which works fine).  But it does not cover unit testing in any way.  I don't think this ticket should be closed.

As it stands, unit testing viewmodels is not possible when using webpack and plugins are involved (or at least the solution on how to do it is not documented).

**Comment by stevies** [comment]
Should this be raised as a defect against aurelia/testing?  It does not appear to work when using webpack.

**Comment by stevies** [comment]
Ah - I now see this is really much the same as: 

https://github.com/aurelia/testing/issues/21

But with ES6 and not typescript.  That has also been closed (which is why I originally did not see it) and moved to: 

https://github.com/aurelia/loader-webpack/issues/19

**Comment by thinkOfaNumber** [comment]
I'm still getting this error with the latest skeleton-typescript-webpack.

I added a component "my-component" from the docs http://aurelia.io/hub.html#/doc/article/aurelia/testing/latest/testing-components/3 and tried to test it, and I get the error:

        Error: Cannot call ComponentTester.dispose() before ComponentTester.create()
            at ComponentTester.dispose (test/karma-bundle.js:36507:13)
            at Object.<anonymous> (test/karma-bundle.js:36759:19)
            at Object.fn (test/karma-bundle.js:35687:44)
    Chrome 58.0.3029 (Windows 7 0.0.0): Executed 1 of 13 (1 FAILED) (0 secs / 4.999 secs)
    Chrome 58.0.3029 (Windows 7 0.0.0) MyComponent should render first name FAILED
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        Error: Cannot call ComponentTester.dispose() before ComponentTester.create()
            at ComponentTester.dispose (test/karma-bundle.js:36507:13)
            at Object.<anonymous> (test/karma-bundle.js:36759:19)
            at Object.fn (test/karma-bundle.js:35687:44)

All other tests in the skeleton project work.

#21 and aurelia/loader-webpack#19 seem to reference updates to the skeleton as fixes, but I just pulled the latest and the result is as above.

Any ideas?

**Comment by thinkOfaNumber** [comment]
To reply to myself (and anyone following) my problem was that I _should_ have declared my component like this:

    StageComponent.withResources(PLATFORM.moduleName("path/to/component"));
but I didn't have the `PLATFORM.moduleName`

I also didn't see the resulting error:

    Error: Unable to find module with ID: path/to/component'
because I didn't have a `catch()` handler on the component create method:

    component.create(bootstrap).then(() => {
        ...
        done();
    }).catch(e => { console.log(e.toString()) });

I hope that helps someone!
