### ISSUE TITLE
There is no way to test a component that requires its own transpiled styles

### ISSUE THREAD

**Issue by fracz** [aurelia/testing#43]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.2.0.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.32

* **Browser:**
all

* **Language:**
all

**Current behavior:**
I want to test a component that has CSS import in its view 

```html
<require from="./my-component.css"></require>
```

The test setup is as follows:
```ts
component = StageComponent
      .withResources('src/path/to/my-component')
      .inView('<my-component value.bind="theValue"></my-component>')
      .boundTo({theValue: 'A'});
```

The test starts with `component.create(bootstrap).then(() => {` and fails with 

```
'Potentially unhandled rejection [6] Error: Failed loading required CSS file: http://localhost:9876/base/src/path/to/my-component.css
at fixupCSSUrls (http://localhost:9876/base/jspm_packages/npm/aurelia-templating-resources@1.1.1/css-resource.js:40:13)
    at eval (http://localhost:9876/base/jspm_packages/npm/aurelia-templating-resources@1.1.1/css-resource.js:79:16)
    at F (http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?d692c29342151afdfbd5dbd05e675585d5716dc5:4:7484)
    at H (http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?d692c29342151afdfbd5dbd05e675585d5716dc5:4:7116)
    at q.when (http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?d692c29342151afdfbd5dbd05e675585d5716dc5:4:10787)
    at b.run (http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?d692c29342151afdfbd5dbd05e675585d5716dc5:4:9823)
    at t._drain (http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?d692c29342151afdfbd5dbd05e675585d5716dc5:4:1744)
    at drain (http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?d692c29342151afdfbd5dbd05e675585d5716dc5:4:1398)
    at MutationObserver.e (http://localhost:9876/base/node_modules/systemjs/dist/system-polyfills.js?d692c29342151afdfbd5dbd05e675585d5716dc5:4:3319)'

	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
	Error: Cannot call ComponentTester.dispose() before ComponentTester.create()
	    at ComponentTester.dispose (jspm_packages/npm/aurelia-testing@1.0.0-beta.2.0.0/component-tester.js:89:15)
	    at Object.eval (src/path/to/my-component.spec.ts!transpiled:46:31)
```

The CSS file is not there because I use SCSS and it gets transpiled during build.

**Expected/desired behavior:**
 I wish I could somehow turn-off styles loading in unit tests. They are really not needed there...

**Comment by timfish** [comment]
I've had this same issue. I thought maybe I could override the Loader and return an empty string:

```typescript
class EmptyCssLoader extends DefaultLoader {
  constructor() {
    super();
  }

  loadText(url: string): Promise<string> {
    return url.endsWith('.css')
      ? Promise.resolve('')
      : super.loadText(url);
  }
}
```

```typescript
  beforeEach(() => {
    component = StageComponent
      .withResources('src/layout/title-bar')
      .inView('<title-bar></title-bar>');

    component.bootstrap((aurelia: Aurelia) => {
      aurelia.use.standardConfiguration();
      aurelia.container.registerInstance(Loader, new EmptyCssLoader());
    });
  });
```

However it appears that only `html` files are going through my `EmptyCssLoader`. The Css loading is still getting an instance of `DefaultLoader` from the di container.

**Comment by fracz** [comment]
We went for a compromise, i.e. we still have small scss files near to the components where they are used, but gulp finds all of them during build, concatenates them and serves as one `style.css` file. This allowed us to remove all `<require from="*.css">` from views. 

Now, we can have CSS hot reload with browsersync and unit test a components. Both of these were not possible with _cool_ `require` tags.

**Comment by Alexander-Taran** [comment]
Possible with jest to mock out 'modules' by pattern name..

https://github.com/justinsisley/Jest-CSS-Modules
