### ISSUE TITLE
Named slots cause DI exception

### ISSUE THREAD

**Issue by AdamWillden** [aurelia/testing#57]
**I'm submitting a bug report**

Could be related to https://github.com/aurelia/pal-browser/issues/17 ??

* **Library Version:**
1.0.0-beta.2.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.4.0

* **NPM Version:**
4.0.5

* **JSPM OR Webpack AND Version**
JSPM 0.17.0-beta.32

* **Browser:**
Chrome 56.0.2924

* **Language:**
TypeScript 2.1.5

**Current behavior:**
The existence of a named slot produces a DI error (default slots do not):

```
Chrome 56.0.2924 (Windows 10 0.0.0) Given the collapsible-island custom element when the header slot is overridden then the header slow is appropriately displayed FAILED
        ------------------------------------------------
        Inner Error:
        Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
        Inner Error Stack:
        Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
            at validateKey (http://localhost:9876/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:9:23147)
            at Container.get (http://localhost:9876/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:9:34764)
            at Container.elementContainerGet [as get] (http://localhost:9876/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:9:127398)
            at Object.invoke (http://localhost:9876/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:9:25855)
            at InvocationHandler.invoke (http://localhost:9876/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:9:24554)
            at Container.invoke (http://localhost:9876/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:9:39291)
            at ProviderResolver.get (http://localhost:9876/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:9:123852)
            at Container.get (http://localhost:9876/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:9:36206)
            at Container.elementContainerGet [as get] (http://localhost:9876/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:9:127398)
            at HtmlBehaviorResource.create (http://localhost:9876/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:9:255431)
        End Inner Error Stack
        ------------------------------------------------
            at ProviderResolver.get (http://localhost:9876/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:9:123852)
            at Container.get (http://localhost:9876/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:9:36206)
            at Container.elementContainerGet [as get] (http://localhost:9876/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:9:127398)
            at HtmlBehaviorResource.create (http://localhost:9876/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:9:255431)
        Error: Error invoking SlotCustomAttribute. Check the inner error for details.
            at new AggregateError (http://localhost:9876/jspm_packages/npm/aurelia-pal@1.2.0/aurelia-pal.js:9:2205)
            at Container.invoke (http://localhost:9876/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:9:39380)
            at applyInstructions (http://localhost:9876/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:9:133310)
            at ViewFactory.create (http://localhost:9876/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:9:146769)
            at TemplatingEngine.enhance (http://localhost:9876/jspm_packages/npm/aurelia-templating@1.2.0/aurelia-templating.js:9:304366)
            at eval (http://localhost:9876/jspm_packages/npm/aurelia-framework@1.0.8/aurelia-framework.js:9:11704)
        Error: No element with class 'qa-collapsible-island-header' found.
            at getHeaderText (http://localhost:9876/test/unit/collapsible-island.spec.ts!transpiled:9:7816)
            at Object.eval (http://localhost:9876/test/unit/collapsible-island.spec.ts!transpiled:9:17140)
            at Object.arguments.(anonymous function) (http://localhost:9876/jspm_packages/npm/jasmine-promises@0.4.1/dist/jasmine-promises.js:9:4150)
            at eval (http://localhost:9876/jspm_packages/npm/jasmine-promises@0.4.1/dist/jasmine-promises.js:9:4881)
            at tryCatchReject (jspm_packages/system-polyfills.src.js:1188:30)
        Error: Cannot call ComponentTester.dispose() before ComponentTester.create()
            at ComponentTester.dispose (http://localhost:9876/jspm_packages/npm/aurelia-testing@1.0.0-beta.2.0.1/component-tester.js:9:4657)
            at Object.eval (http://localhost:9876/test/unit/collapsible-island.spec.ts!transpiled:9:16937)
            at Object.arguments.(anonymous function) (http://localhost:9876/jspm_packages/npm/jasmine-promises@0.4.1/dist/jasmine-promises.js:9:4150)
Chrome 56.0.2924 (Windows 10 0.0.0): Executed 8 of 8 (1 FAILED) (4.766 secs / 2.346 secs)
```
This code causes the exception
```
escribe('when the header slot is overridden', () => {
    let model = {
      collapsed: false
    };

    beforeEach(async () => {
      component = component
        .inView(`<collapsible-island><div slot="header" class="${qaHeader}">Replacement Content</div></collapsible-island>`)
        .boundTo(model);
      await component.create(bootstrap as any);
    });

    afterEach(() => {
      component.dispose();
    });

    it('then the header slow is appropriately displayed', () => {
      expect(getHeaderText()).toBe('Replacement Content');
    });
  });
```

This code does not cause the exception (note the missing `slot="header"`)
```
describe('when the header slot is overridden', () => {
    let model = {
      collapsed: false
    };

    beforeEach(async () => {
      component = component
        .inView(`<collapsible-island><div class="${qaHeader}">Replacement Content</div></collapsible-island>`)
        .boundTo(model);
      await component.create(bootstrap as any);
    });

    afterEach(() => {
      component.dispose();
    });

    it('then the header slow is appropriately displayed', () => {
      expect(getHeaderText()).toBe('Replacement Content');
    });
  });
```

**Expected/desired behavior:**

* **What is the expected behavior?**
aurelia-testing should support named slots

**Comment by AdamWillden** [comment]
I will keep investigating in case there is an issue on my part

**Comment by AdamWillden** [comment]
@niieani I have PMed you on gitter with a repro which may help the linked issue where you asked for one.

**Comment by ajoslin103** [comment]
"This is not the issue you're looking for..."

comment moved to #54 

thanks

**Comment by AdamWillden** [comment]
I think that is more #54 than this bug. I do not see any named slots in your code.

**Comment by jmzagorski** [comment]
i am also having the same issue with webpack. I included my project.json aurelia/jasmine/karma related dependencies and my test. It seems that after the `SlotCustomAttribute` is found in the container but it has an `undefined` dependency that is created in the `Container.Prototype.._createInvocationHandler(fn)`. Not sure if that helps any.

```
  "dependencies": {
    "aurelia-bootstrapper": "^2.0.1",
    "aurelia-fetch-client": "^1.0.1",
    "aurelia-framework": "^1.1.0",
    "aurelia-loader-webpack": "^2.0.0",
    "aurelia-logging-console": "1.0.0",
    "aurelia-pal": "^1.3.0",
    "aurelia-polyfills": "1.2.1",
    "aurelia-router": "^1.2.1"
  },
  "devDependencies": {
    "@types/node": "^7.0.12",
    "aspnet-webpack": "^1.0.28",
    "aurelia-testing": "1.0.0-beta.3.0.1",
    "aurelia-tools": "1.0.0",
    "aurelia-webpack-plugin": "^2.0.0-rc.2",
    "jasmine-core": "2.6.1",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.1.1",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "1.1.0",
    "karma-mocha-reporter": "2.2.3",
    "karma-webpack": "2.0.3",
    "webpack": "^2.6.1",
    "webpack-hot-middleware": "^2.18.0"
  }
```

```
  it('constructs an entire card with slots', async done => {
    component.inView(`<lms-card has-actions.bind="true">
      <span id="title" slot="title"></span>
      </lms-card>`)

    debugger;
    await component.create(bootstrap);

    const titleElem = document.querySelector('.card-title > #title');
    expect(titleElem).not.toEqual(null);
    done();
  });
```

**Comment by AdamWillden** [comment]
Going to close this. Not sure if it was fixed in a dependency change or my move to jest but I uncommented the test and it passed without exception.

**Comment by AdamWillden** [comment]
It may be that now I'm using jest I also import `aurelia-pal-nodejs` and call `globalize()` which may be the same fix as is mentioned in issue [aurelia/pal-browser#17](https://github.com/aurelia/pal-browser/issues/17) referenced above.
